name: Build and Deploy to CloudHub 2.0 DEV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=.m2/repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java 17 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -DskipTests

      - name: Rename artifact with Git commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactBaseName=$(basename "$artifactName1" .jar)
          artifactName2="${artifactBaseName}-${commitHash}.jar"
          mv "$artifactName1" "target/$artifactName2"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact

      - name: Deploy to CloudHub 2.0 DEV
        env:
          CONNECTED_CLIENT_ID: ${{secrets.CONNECTED_APPS_CLIENT_ID}}
          CONNECTED_CLIENT_SECRET: ${{secrets.CONNECTED_APPS_CLIENT_SECRET}}
          CLIENT_ID: ${{secrets.DEV_CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.DEV_CLIENT_SECRET}}
          ENV: ${{secrets.DEV_ENV}}
          VCORES: ${{secrets.DEV_VCORES}}
          TARGET: ${{secrets.DEV_TARGET}}
          MULE_ENV: ${{secrets.DEV_MULE_ENV}}
          REPLICAS: ${{secrets.DEV_REPLICAS}}
          SECRET_KEY: ${{secrets.DEV_SECRET_KEY}}
        run: |
          artifactName=$(ls *.jar | head -1)
          echo "Deploying artifact: $artifactName"
          mvn deploy -e -s settings.xml $MAVEN_OPTS \
            -DmuleDeploy \
            -Dmule.artifact="$artifactName" \
            -Denvironment="$ENV" \
            -DvCores="$VCORES" \
            -Dtarget="$TARGET" \
            -Dmule.env="$MULE_ENV" \
            -Dreplicas="$REPLICAS" \
            -Danypoint.platform.client_id="$CLIENT_ID" \
            -Danypoint.platform.client_secret="$CLIENT_SECRET" \
            -DconnectedAppClientId="$CONNECTED_CLIENT_ID" \
            -DconnectedAppClientSecret="$CONNECTED_CLIENT_SECRET" \
            -Dmule.key="$SECRET_KEY" \
            -DskipTests
